$engine: 3
$onesync: on
name: ESX Legacy
author: ESX Framework
description: The official recipe of the most popular FiveM RP framework, containing Jobs, Housing, Vehicles & more!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/esx-framework/esx-recipes
    ref: legacy
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/esxLogo.png
    dest: ./esxLogo.png

  # Download basic resources and ESX dependencies

  - action: connect_database

  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql

  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons/
    ref: main
    dest: ./tmp/addons

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[core]

  - action: move_path
    src: ./tmp/addons/[esx_addons]
    dest: ./resources/[esx_addons]

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql.zip

  ## Cleanup
  - action: remove_path
    path: ./tmp
